# Small config to help refactoring to make the model completely YAML based
defaults:
  experiment:
    model_file: ../exp/mar18_phoneme_to_image_norm_over_concept/output/<EXP>.mod
    hyp_file: ../exp/mar18_phoneme_to_image_norm_over_concept/output/<EXP>.hyp
    out_file: ../exp/mar18_phoneme_to_image_norm_over_concept/output/<EXP>.out
    err_file: ../exp/mar18_phoneme_to_image_norm_over_concept/output/<EXP>.err
    run_for_epochs: 20
    eval_metrics: recall|nbest=1,recall|nbest=5,recall|nbest=10
  train:
    trainer: adam
    learning_rate: 0.001
    default_layer_dim: 512
    dropout: 0.0
    dev_metrics: recall|nbest=1,recall|nbest=5,recall|nbest=10
    training_corpus: !BilingualTrainingCorpus
      train_src: ../../data/flickr30k/phoneme_level/src_flickr30k.train
      train_trg: ../../data/flickr30k/phoneme_level/flickr30k.train.ids
      train_id_file: ../../data/flickr30k/phoneme_level/flickr30k.train.ids
      dev_src: ../../data/flickr30k/phoneme_level/src_flickr30k.test
      dev_trg: ../../data/flickr30k/phoneme_level/flickr30k.test.ids
      dev_id_file: ../../data/flickr30k/phoneme_level/flickr30k.test.ids
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !IDReader {}
    model: !EncDecRetriever
      translator: !DefaultTranslator
        src_embedder: !SimpleWordEmbedder
          vocab_size: 20000 # TODO: set this automatically
          emb_dim: 512
        encoder: !LSTMEncoder
          layers: 1
        attender: !StandardAttender
          hidden_dim: 512
          state_dim: 512
          input_dim: 512  
        trg_embedder: !SimpleWordEmbedder
          vocab_size: 20000 # TODO: set this automatically
          emb_dim: 512
        decoder: !MlpSoftmaxDecoder
          layers: 1
          mlp_hidden_dim: 512
          vocab_size: 20000 # TODO: set this automatically
      database: !StandardRetrievalDatabase
        reader: !PlainTextReader {}
        database_file: ../../data/flickr30k/phoneme_level/trg_flickr30k.all
  decode:
    src_file: ../../data/flickr30k/phoneme_level/src_flickr30k.test
    len_norm_type: PolynomialNormalization 
    candidate_id_file: ../../data/flickr30k/phoneme_level/flickr30k.test.ids
   
  evaluate:
    ref_file: ../../data/flickr30k/phoneme_level/flickr30k.test.ids

phoneme_to_concept_retrieval:
  train:
     dropout: 0.0
