defaults:
  experiment:
    model_file: ../exp/feb28_phoneme_level_clustering/output/<EXP>.mod
    hyp_file: ../exp/feb28_phoneme_level_clustering/output/<EXP>.hyp
    out_file: ../exp/feb28_phoneme_level_clustering/output/<EXP>.out
    err_file: ../exp/feb28_phoneme_level_clustering/output/<EXP>.err
    run_for_epochs: 20
    eval_metrics: wer
  train:
    default_layer_dim: 512
    restart_trainer: True
    trainer: Adam
    learning_rate: 0.0002
    lr_decay: 0.5
    dev_metrics: wer
    training_corpus: !BilingualTrainingCorpus
      train_src: ../../data/flickr30k/phoneme_level/src_flickr30k.txt #train.ja
      train_trg: ../../data/flickr30k/phoneme_level/trg_flickr30k.txt  #train.en
      dev_src: ../../data/flickr30k/phoneme_level/src_flickr30k.txt #dev.ja
      dev_trg: ../../data/flickr30k/phoneme_level/trg_flickr30k.txt    
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !PlainTextReader {}
    model: !WordDiscoverer
      src_embedder: !SimpleWordEmbedder
        emb_dim: 512
      encoder: !LSTMEncoder
        layers: 1
      attender: !ClusterAttender
        hidden_dim: 512
        state_dim: 512
        input_dim: 512
      trg_embedder: !SimpleWordEmbedder
        emb_dim: 512
      decoder: !MlpSoftmaxDecoder
        layers: 1
        mlp_hidden_dim: 512
      trg_data: !StandardRetrievalDatabase
        reader: !PlainTextReader {}
        database_file: ../../data/flickr30k/phoneme_level/trg_flickr30k.txt
  decode:
    src_file: ../../data/flickr30k/phoneme_level/src_flickr30k.txt #test.ja
    report_path: ../exp/feb28_phoneme_level_clustering/<EXP>
  evaluate:
    ref_file: ../../data/flickr30k/phoneme_level/flickr30k_alignment.ref #test.en

word_discovery_dropout-0.1:
  train:
    dropout: 0.1
